{{- if .Values.versionExporter.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "qubership-version-exporter.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - secrets
    verbs:
      - 'get'
      - 'list'
      - 'watch'
{{- end }}
