{{- if .Values.versionExporter.install }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "qubership-version-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "qubership-version-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "qubership-version-exporter.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}