{{- if and .Values.versionExporter.install .Values.versionExporter.extraVarsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.versionExporter.secretName}}
type: Opaque
stringData:
  {{- range $key, $val := .Values.versionExporter.extraVarsSecret }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
  {{- end}}
{{- end }}
