{{- if and .Values.versionExporter.install .Values.versionExporter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qubership-version-exporter.serviceAccountName" . }}
  labels:
    app: {{ template "qubership-version-exporter.name" . }}
    app.kubernetes.io/name: {{ template "qubership-version-exporter.name" . }}
    {{- if .Values.versionExporter.service.labels }}
      {{ toYaml .Values.versionExporter.service.labels | indent 4 }}
    {{- end }}
  {{- if .Values.versionExporter.serviceAccount.annotations }}
  annotations:
  {{ toYaml .Values.versionExporter.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
